### ISSUE TITLE
The each sections overlaps in the side wise and top bottom wise 

### ISSUE THREAD

**Issue by aryagovindannair** [jenish963/demo-design#1]
There is no separation between each sections 

![R2](https://github.com/jenish963/demo-design/assets/161284141/0b0f6470-c1fd-4203-872c-adb6ccd42b8f)

**Comment by jenish963** [comment]
this issue is now fixed.
![Screenshot 2024-06-03 095737](https://github.com/jenish963/demo-design/assets/121596406/bf7ec21d-df3b-4213-a34f-938dacd28a74)
