### ISSUE TITLE
There should be a separate section 

### ISSUE THREAD

**Issue by aryagovindannair** [jenish963/demo-design#2]
Not like that as the original one 

![R1](https://github.com/jenish963/demo-design/assets/161284141/389c9a12-38f9-49da-991d-182425a3b420)

**Comment by jenish963** [comment]
fixed now.
![Screenshot 2024-06-03 095836](https://github.com/jenish963/demo-design/assets/121596406/ca59ec9e-3fcf-48da-8826-187a1de41910)
