### ISSUE TITLE
Section with figure is missing 

### ISSUE THREAD

**Issue by aryagovindannair** [jenish963/demo-design#3]
![R4](https://github.com/jenish963/demo-design/assets/161284141/ff08eec5-76fa-4501-86b2-b61cde11fc26)

**Comment by jenish963** [comment]
added figure with names.
![Screenshot 2024-06-03 103822](https://github.com/jenish963/demo-design/assets/121596406/e0df8d6b-be11-4e33-92bd-ea5243feabe5)
